### ISSUE TITLE
Problem setting gutter to zero

### ISSUE THREAD

**Issue by rolandtoth** [juliancwirko/s-grid#10]
Gutter value 0 doesn't seem to work:

`cell(2, 3, g: 0)`

However, using 0.0001 works. Is there something I miss or is this a bug?

**Comment by juliancwirko** [comment]
Hi, are you sure that you don't have any other styles which could overwrite gutter styles? Maybe some paddings or margins on the same element?

**Comment by rolandtoth** [comment]
Yes, it's a new project with almost no styles. Plus the devtools shows 'invalid property value':

`flex-basis: calc(100% * .25 - 0)`

In case of 0.00001 it looks like this (it's a 1/4 col):

`flex-basis: calc(100% * .25 - 6.25e-7rem)`

**Comment by juliancwirko** [comment]
Ok, that's weird ;) I'll debug this asap.

**Comment by juliancwirko** [comment]
I've tested it using something like:

```stylus
@import 's-grid-settings'
@import 's-grid-functions'

.grid
  grid()
  .cell
    cell(1, 3, g: 0)
```
And it produces me something like: 

```css
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}
.grid {
  display: flex;
  flex-wrap: wrap;
  align-items: flex-start;
  flex-direction: row;
}
.grid .cell {
  flex-basis: calc(100% * 0.333333333333333 - 0rem);
  min-width: 0;
}
```
So it seems to work well. The output in the browser is also good in both cases with and without gutter.
